### ISSUE TITLE
DeviceProfile: allAppsIconSizePx is 0 right after startup

### ISSUE THREAD

**Issue by felicss** [amirzaidi/Launcher3#296]
When compiling an launching the apk, it crashes because the iconSizePx is always 0 and it tries to divide by that value. Any idea why?

* Device: Samsung Galaxy S8
* Android version: 7.0
* Launcher version: latest

## Logcat
```
  java.lang.ArithmeticException: divide by zero
        at xyz.klinker.blur.launcher3.allapps.AllAppsRecyclerView.setNumAppsPerRow(AllAppsRecyclerView.java:96)
        at xyz.klinker.blur.launcher3.allapps.AllAppsContainerView.onMeasure(AllAppsContainerView.java:393)
        at android.view.View.measure(View.java:21045)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:21045)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:21045)
        at xyz.klinker.blur.addons.view.LauncherDrawerLayout.onMeasure(LauncherDrawerLayout.java:704)
        at android.view.View.measure(View.java:21045)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:21045)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:21045)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:849)
        at android.view.View.measure(View.java:21045)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2576)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1635)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1886)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7091)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
        at android.view.Choreographer.doFrame(Choreographer.java:638)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by amirzaidi** [comment]
Try compiling with Gradle 2.3, I know 3.0 causes problems like this

**Comment by amirzaidi** [comment]
Fixed by disabling AAPT 2 for now
