### ISSUE TITLE
Error while starting app from build

### ISSUE THREAD

**Issue by antoxa2584x** [amirzaidi/Launcher3#374]
```
FATAL EXCEPTION: main
Process: com.google.android.apps.nexuslauncher, PID: 24140
java.lang.RuntimeException: Unable to get provider com.google.android.apps.nexuslauncher.search.AppSearchProvider: java.lang.ArithmeticException: divide by zero
    at android.app.ActivityThread.installProvider(ActivityThread.java)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
    at android.app.ActivityThread.-wrap2(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
    at android.os.Handler.dispatchMessage(Handler.java)
    at android.os.Looper.loop(Looper.java)
    at android.app.ActivityThread.main(ActivityThread.java)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
 Caused by: java.lang.ArithmeticException: divide by zero
    at com.android.launcher3.DeviceProfile.calculateCellWidth(DeviceProfile.java:596)
    at com.android.launcher3.DeviceProfile.getCellSize(DeviceProfile.java:496)
    at com.android.launcher3.DeviceProfile.updateIconSize(DeviceProfile.java:363)
    at com.android.launcher3.DeviceProfile.updateAvailableDimensions(DeviceProfile.java:342)
    at com.android.launcher3.DeviceProfile.<init>(DeviceProfile.java:254)
    at com.android.launcher3.InvariantDeviceProfile.<init>(InvariantDeviceProfile.java:172)
    at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:98)
    at com.android.launcher3.LauncherAppState.getInstance(LauncherAppState.java:60)
    at com.google.android.apps.nexuslauncher.search.AppSearchProvider.onCreate(AppSearchProvider.java:136)
    at android.content.ContentProvider.attachInfo(ContentProvider.java)
    at android.content.ContentProvider.attachInfo(ContentProvider.java)
    at android.app.ActivityThread.installProvider(ActivityThread.java) 
    at android.app.ActivityThread.installContentProviders(ActivityThread.java) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java) 
    at android.app.ActivityThread.-wrap2(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
    at android.os.Handler.dispatchMessage(Handler.java) 
    at android.os.Looper.loop(Looper.java) 
    at android.app.ActivityThread.main(ActivityThread.java) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
```

**Comment by amirzaidi** [comment]
Don't update Gradle to 3, I haven't made it compatible with Gradle 3 yet.
