### ISSUE TITLE
No icon on home screen

### ISSUE THREAD

**Issue by mohamnexus** [amirzaidi/Launcher3#509]
Hi,
Thanks for launcher,
On my phone, after installed it, home screen haven't icon (none) (only show bottom search bar)
My phone: HTC Desire 825 (Android 6.0.1)
I got this error(my log):

`        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2824)
        at android.content.res.Resources.getXml(Resources.java:1222)
        at com.android.launcher3.shortcuts.DeepShortcutManagerBackport.parsePackageXml(DeepShortcutManagerBackport.java:120)
        at com.android.launcher3.shortcuts.DeepShortcutManagerBackport.getForPackage(DeepShortcutManagerBackport.java:55)
        at com.android.launcher3.shortcuts.DeepShortcutManager.query(DeepShortcutManager.java:238)
        at com.android.launcher3.shortcuts.DeepShortcutManager.queryForAllShortcuts(DeepShortcutManager.java:193)
        at com.android.launcher3.model.LoaderTask.loadDeepShortcuts(LoaderTask.java:850)
        at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:185)
W:     at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:168)
        at android.os.HandlerThread.run(HandlerThread.java:61)
W: Failure getting entry for 0x7f14000a (t=19 e=10) (error -75)
W: android.content.res.Resources$NotFoundException: Resource ID #0x7f14000a
        at android.content.res.Resources.getValue(Resources.java:1359)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2824)
        at android.content.res.Resources.getXml(Resources.java:1222)
        at com.android.launcher3.shortcuts.DeepShortcutManagerBackport.parsePackageXml(DeepShortcutManagerBackport.java:120)
        at com.android.launcher3.shortcuts.DeepShortcutManagerBackport.getForPackage(DeepShortcutManagerBackport.java:55)
        at com.android.launcher3.shortcuts.DeepShortcutManager.query(DeepShortcutManager.java:238)
        at com.android.launcher3.shortcuts.DeepShortcutManager.queryForAllShortcuts(DeepShortcutManager.java:193)
        at com.android.launcher3.model.LoaderTask.loadDeepShortcuts(LoaderTask.java:850)
W:     at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:185)
        at android.os.Handler.handleCallback(Handler.java:739)
W:     at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:168)
        at android.os.HandlerThread.run(HandlerThread.java:61)
`

**Comment by mohamnexus** [comment]
Hi,
I found this log isn't for show icon and when i fix it (this error for some apps like "Trello" and uninstall it, so it fixed), but i haven't icon on screen again and it has bug :(
(On galaxy note 3 - Android 5 some icon on screen not loaded - like chrome)

I think this part need check.
