### ISSUE TITLE
Pixel Launcher rolling crash on startup, resource missing?

### ISSUE THREAD

**Issue by anaisbetts** [amirzaidi/Launcher3#510]
This started happening all of a sudden on my phone, seems like an update has caused it somehow?

```
06-11 13:41:31.751 21435 21456 E AndroidRuntime: java.lang.NumberFormatException: For input string: "mipmap/ic_launcher_round"
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at java.lang.Integer.parseInt(Integer.java:608)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at java.lang.Integer.parseInt(Integer.java:643)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.google.android.apps.nexuslauncher.CustomIconProvider.getRoundIcon(Unknown Source:174)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.google.android.apps.nexuslauncher.CustomIconProvider.getIcon(Unknown Source:143)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.android.launcher3.IconCache.getFullResIcon(Unknown Source:4)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.android.launcher3.IconCache.cacheLocked(Unknown Source:48)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.android.launcher3.IconCache.getTitleAndIcon(Unknown Source:11)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.android.launcher3.IconCache.getTitleAndIcon(Unknown Source:6)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.android.launcher3.AllAppsList.add(Unknown Source:26)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.android.launcher3.model.LoaderTask.loadAllApps(Unknown Source:86)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at com.android.launcher3.model.LoaderTask.run(Unknown Source:2275)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-11 13:41:31.751 21435 21456 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
```

Phone Model: Samsung Galaxy S9 (SM-G960U), let me know if I can look anything else up out of `getprop` or debug in some other way.

**Comment by noahmjohnson** [comment]
Getting this on the Samsung Galaxy S8, (SM-G950U) as well.

**Comment by micha3lpaul** [comment]
This started happening today on a Samsung Galaxy S7 here also.  I modified CustomIconProvider.java:159 to catch NumberFormatException in order to get my wife's phone (and her) happy again.

**Comment by newo32** [comment]
Same here -- problem started today on a Galaxy S9. Launcher just crashes until the phone auto-sets a different launcher as default in response.

**Comment by newo32** [comment]
For what it's worth, this started happening immediately after I updated to the newest version of the Google app.

**Comment by amirzaidi** [comment]
Try the new update and close the issue if it has been resolved

**Comment by newo32** [comment]
Dude, amazing. Thank you so much for fixing this! Absolutely LOVE using
your launcher on my S9.
