### ISSUE TITLE
Workspace onDropCompleted crash

### ISSUE THREAD

**Issue by skyscrapy** [amirzaidi/Launcher3#542]
Fatal Exception: java.lang.RuntimeException: Invalid state: cellLayout == null in Workspace#onDropCompleted. Please file a bug. 
       at com.android.launcher3.Workspace.onDropCompleted(Workspace.java:3614)
       at com.android.launcher3.dragndrop.DragController.cancelDrag(DragController.java:254)
       at com.android.launcher3.dragndrop.DragController.onAppsRemoved(DragController.java:267)
       at com.android.launcher3.Launcher.bindWorkspaceComponentsRemoved(Launcher.java:4174)
       at com.android.launcher3.model.PackageUpdatedTask$4.execute(PackageUpdatedTask.java:349)
       at com.android.launcher3.LauncherModel$BaseModelUpdateTask$1.run(LauncherModel.java:1980)
       at com.android.launcher3.DeferredHandler$Impl.handleMessage(DeferredHandler.java:49)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by amirzaidi** [comment]
Stop opening duplicate issues.

https://github.com/amirzaidi/Launcher3/issues/546

https://github.com/amirzaidi/Launcher3/issues/550

I asked you in one of your other issues "How do I reproduce this?" but you did not respond.

**Comment by skyscrapy** [comment]
It doesn't always happen, but it did occur

**Comment by skyscrapy** [comment]
Some users report these bugs. Of coz you can just ignore. I'll fix them later by myself
