### ISSUE TITLE
drop crash

### ISSUE THREAD

**Issue by skyscrapy** [amirzaidi/Launcher3#546]
Fatal Exception: java.lang.RuntimeException: item: be(id=14 type=0 container=-100 screen=0 cellX=4 cellY=4 spanX=1 spanY=1 minSpanX=1 minSpanY=1 rank=0 user=UserHandle{0} title=Flashlight)modelItem: be(id=14 type=0 container=-100 screen=0 cellX=4 cellY=3 spanX=1 spanY=1 minSpanX=1 minSpanY=1 rank=0 user=UserHandle{0} title=Flashlight)Error: ItemInfo passed to checkItemInfo doesn't match original
       at com.android.launcher3.model.ModelWriter$UpdateItemBaseRunnable.(ModelWriter.java:329)
       at com.android.launcher3.model.ModelWriter$UpdateItemRunnable.(ModelWriter.java:281)
       at com.android.launcher3.model.ModelWriter.modifyItemInDatabase(ModelWriter.java:188)
       at com.android.launcher3.CellLayout.commitTempPlacement(CellLayout.java:2148)
       at com.android.launcher3.CellLayout.performReorder(CellLayout.java:2391)
       at com.android.launcher3.Workspace.onDrop(Workspace.java:2593)
       at com.android.launcher3.dragndrop.DragController.drop(DragController.java:581)
       at com.android.launcher3.dragndrop.DragController.onDriverDragEnd(DragController.java:382)
       at com.android.launcher3.dragndrop.DragDriver.onTouchEvent(DragDriver.java:57)
       at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(DragController.java:524)
       at com.android.launcher3.dragndrop.DragLayer.onTouchEvent(DragLayer.java:371)
       at android.view.View.dispatchTouchEvent(View.java:10026)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2629)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2635)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2635)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2635)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2635)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3076)
       at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:3038)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
       at android.view.View.dispatchPointerEvent(View.java:10246)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4456)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4324)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3871)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3924)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3890)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4017)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3898)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4074)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3871)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3924)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3890)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3898)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3871)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6317)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6256)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6217)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6420)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6391)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6443)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:615)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6196)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by amirzaidi** [comment]
How do I reproduce this?
